### ISSUE TITLE
Standard classes processed as CDI bean?

### ISSUE THREAD

**Issue by jefrajames** [kumuluz/kumuluzee-graphql#4]
Hi, I've done a test with CDI and bean-discovery-mode set to annotated. In that context, standard Java classes (non-CDI beans) annotated with @GraphQLClass are treated as non-contextual CDI beans (based on Unmanaged CDI bean) in GraphQLServlet and implicitly benefit from some CDI injection. Is it a an expected behavior?
Furthermore, CDI beans are also instanciated as non-contextual. And according to that [article]( http://javadox.com/org.jboss.weld/weld-core/2.2.4.Final/javax/enterprise/inject/spi/Unmanaged.html), it is said that "_Unmanaged.UnmanagedInstances created by this class are not suitable for sharing between threads_". 
My proposal would be to instanciate non CDI-beans using Java new() and to get references on CDI beans using the BeanManager. What do you think?

**Comment by jmezna** [comment]
Thank you for your observation. Your suggestion seems reasonable, so we implemented the changes and are currently testing the new version.

If everything will work as expected, we will publish the patch shortly.

**Comment by jmezna** [comment]
Fixed in v1.0.2.
